### ISSUE TITLE
Benefit of this adapter / readme

### ISSUE THREAD

**Issue by smartboart** [Pmant/ioBroker.fakeroku#16]
Sorry for my issue... But what is the benefit of this adapter.. What can I do with it... What is it for...

**Comment by foxriver76** [comment]
Mainly, to acknowledge which button on your Harmony remote has been pressed. eg  you could control your Homematic thermostat (or any other device connected to ioB) via your harmony remote, this adapter and a short script.

**Comment by smartboart** [comment]
Thank you very much...
